// <auto-generated />
using System;
using HomeChecklist.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeChecklist.Persistence.Migrations
{
    [DbContext(typeof(HomeChecklistDbContext))]
    [Migration("20180706003851_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HomeChecklist.Persistence.Entities.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("HomeChecklist.Persistence.Entities.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HomeId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("HomeChecklist.Persistence.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HomeId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HomeChecklist.Persistence.Entities.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Interval");

                    b.Property<DateTime>("LastDone");

                    b.Property<string>("Name");

                    b.Property<int?>("RoomId");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("HomeChecklist.Persistence.Entities.Resident", b =>
                {
                    b.HasOne("HomeChecklist.Persistence.Entities.Home")
                        .WithMany("Residents")
                        .HasForeignKey("HomeId");
                });

            modelBuilder.Entity("HomeChecklist.Persistence.Entities.Room", b =>
                {
                    b.HasOne("HomeChecklist.Persistence.Entities.Home")
                        .WithMany("Rooms")
                        .HasForeignKey("HomeId");
                });

            modelBuilder.Entity("HomeChecklist.Persistence.Entities.Task", b =>
                {
                    b.HasOne("HomeChecklist.Persistence.Entities.Room")
                        .WithMany("Tasks")
                        .HasForeignKey("RoomId");
                });
#pragma warning restore 612, 618
        }
    }
}
