version: "3.2"
services:
  db:
    image: microsoft/mssql-server-linux
    ports: 
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_DB=HomeChecklistDb
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=correctHorseBatteryStaple1
      - SA_PASSWORD=correctHorseBatteryStaple1
  api:
    image: microsoft/dotnet:sdk
    working_dir: /app/api/
    volumes:
      - ./src/api/:/app/api/
    ports:
      - "5000:5000"
    entrypoint: dotnet watch --project /app/api/HomeChecklist/HomeChecklist.csproj run
    depends_on:
      - db
  web:
    image: teracy/angular-cli
    working_dir: /app/web
    volumes:
      - ./src/web/HomeChecklist/:/app/web/
    ports:
      - "4200:4200"
    entrypoint: ng serve --watch --host 0.0.0.0 --port 4200
    depends_on:
      - api
