version: '0.1.0'
services: 
  api:
    build: ./src/api/
    ports:
      - "5000:80"
  web:
    build: ./src/web/HomeChecklist/
    ports:
      - "4200:80"
  db:
    image: microsoft/mssql-server-linux
    ports: 
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=correctHorseBatteryStaple1