apiVersion: apps/v1
kind: Deployment
metadata:
  name: homechecklist-api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: homechecklist-api
        image: homechecklist-api:latest
        ports:
          containerPort: 5002